### ISSUE TITLE
marc4j in maven central

### ISSUE THREAD

**Issue by jirikrepl** [marc4j/marc4j#53]
Hello,
why marc4j is not in http://search.maven.org/ ? I would make my life simpler. We use marc4j in Moravian Library (2nd biggest in Czech Republic)

Thank for answer

**Comment by terrywbrady** [comment]
Check out https://github.com/ksclarke/freelib-marc4j

**Comment by jirikrepl** [comment]
I know, but it did not work in our project with encoding windows-1250

on this line:https://github.com/jirikrepl/maven-archetype-quickstart-yaz4j/blob/master/src/main/java/quickstartZ3950/App.java#L56

it ends with error
```
Exception in thread "main" org.marc4j.MarcException: Marc record didn't validate
	at org.marc4j.MarcXmlWriter.toXml(MarcXmlWriter.java:454)
	at org.marc4j.MarcXmlWriter.write(MarcXmlWriter.java:428)
	at quickstartZ3950.App.main(App.java:63)
```

**Comment by ksclarke** [comment]
Not to derail this ticket, but would you mind filing a issue with freelib-marc4j detailing what's breaking (with an example record)? Thanks!

**Comment by jirikrepl** [comment]
Sure I just added the reason why we cannot use freelib-marc4j. I just wanted what is the reason why you have release of marc4j at Github and not in Maven central.

**Comment by ksclarke** [comment]
Right. Sorry, I should have been clearer. I'm not with the marc4j/marc4j project (so can't really answer this ticket). I just watch marc4j tickets in case there is anything I should merge into my freelib-marc4j fork. I didn't mean to distract from the purpose of this ticket (getting marc4j/marc4j into Maven central). I'd just like to fix the issue with freelib-marc4j. Thanks. :-)

**Comment by haschart** [comment]
A new version 2.7.3 has been released at GitHub. There are almost no substantive changes in the code. There are massive changes in the formatting to make it consistent throughout and to bring it much closer to the freelib branch. The version has also been pushed to the [Maven Central Repo](http://search.maven.org/#artifactdetails|org.marc4j|marc4j|2.7.3|jar)

**Comment by ksclarke** [comment]
Makes sense to close this issue now that MARC4J is publishing to Maven Central?
