### ISSUE TITLE
Composed characters from Latin 1 Supplement

### ISSUE THREAD

**Issue by bpmph** [marc4j/marc4j#78]
Is there any support for the composed form of the characters in the Latin 1 Supplement ?

We are exporting MARC files in UTF-8 to customers whose systems do not support the decomposed form of some or all of those characters.

We currently create a MARC-File in MARC-8-Format from a MARC-XML (also in MARC-8). Then we convert it to UTF-8 and do the export, like this :

[marc_xml.txt](https://github.com/marc4j/marc4j/files/4029522/marc_xml.txt)

MARCXML -> MARC-8
# java -cp marc4j-2.9.jar org.marc4j.util.XmlMarcDriver -out test/MARC_MARC8.mrc -convert MARC8 marc.xml
MARC-8 -> UTF-8
# java -cp marc4j-2.9.jar org.marc4j.util.UtilDriver to_utf8 test/MARC_MARC8.mrc > test/MARC_UTF8.mrc

or (in one step, with the same result and via java encode tables
# java -cp marc4j-2.9.jar org.marc4j.util.XmlMarcDriver -out test/MARC_UTF8.mrc -encoding UTF8 marc.xml

[MARC_UTF8_mrc.txt](https://github.com/marc4j/marc4j/files/4029524/MARC_UTF8_mrc.txt)
 
The problem in this case are the german umlauts, f.e. the Letter "Ä". It is encoded in its decomposed form (41 CC 88) instead of its composed form (C3 83). The problem extends to other characters which possess a composed form in Latin 1 Supplement (for exaple french vowels)

Since the byte length is different between composed and uncomposed form, any changes after the export would destroy the marc files structure.

We are currently using Version 2.9 of marc4j, with a java 1.6.0_22.

Any advise would be appreciated.

**Comment by haschart** [comment]
I apologize for not seeing this issue earlier.  I am a little confused, but I pretty sure the answer is yes, Marc4j can do what you desire.    

The code you want is in the MarcTranslatedReader  class which can used via the UtilDriver class, by specifying the command line parameter   -normalize   

The following command should do everything you want:
java -jar marc4j-2.9.jar  to_xml  -normalize  test/MARC_MARC8.mrc   >  marc.xml

This command will execute the "default" main program in the jar file, which is org.marc4j.util.UtilDriver,  which will use the next command line parameter to determine what other command to run.    In this case   to_xml    (which actually runs   org.marc4j.util.RecordIODriver  with default parameters of:  -convert xml   )

The RecordIODriver is able to examine the input file you provide and create a properly configured Reader class to read in that marc data.   The subsequent parameters specify additional processing steps to take when the records is being read in or when the results are being written out.   Specifically here the parameter  -normalize  states that the record data should be passed through the MarcTranslatedReader  class with the normalization parameter set to NFC.

So using the above command on the sample file linked to above:   marc_xml.txt   produces a MARCXML file with the Unicode NFC form chosen whenever possible.

Running the output through grep 'Erz'  produces:

      <marc:subfield code="a">Französisch Romane/Erzähl.</marc:subfield>
      <marc:subfield code="e">Erzähler</marc:subfield>
      <marc:subfield code="e">Erzähler</marc:subfield>
      <marc:subfield code="e">Erzähler</marc:subfield>

and running that output through   od  -tx1    shows that the composed form of ö and ä are being used:

```
0000000  20  20  20  20  20  20  3c  6d  61  72  63  3a  73  75  62  66
         sp  sp  sp  sp  sp  sp   <   m   a   r   c   :   s   u   b   f
0000020  69  65  6c  64  20  63  6f  64  65  3d  22  61  22  3e  46  72
          i   e   l   d  sp   c   o   d   e   =   "   a   "   >   F   r
0000040  61  6e  7a[[c3  b6]]73  69  73  63  68  20  52  6f  6d  61  6e
          a   n   z   C   6   s   i   s   c   h  sp   R   o   m   a   n
0000060  65  2f  45  72  7a[[c3  a4]]68  6c  2e  3c  2f  6d  61  72  63
          e   /   E   r   z   C   $   h   l   .   <   /   m   a   r   c
0000100  3a  73  75  62  66  69  65  6c  64  3e  0d  0a  20  20  20  20
          :   s   u   b   f   i   e   l   d   >  cr  nl  sp  sp  sp  sp
0000120  20  20  3c  6d  61  72  63  3a  73  75  62  66  69  65  6c  64
         sp  sp   <   m   a   r   c   :   s   u   b   f   i   e   l   d
0000140  20  63  6f  64  65  3d  22  65  22  3e  45  72  7a[[c3  a4]]68
         sp   c   o   d   e   =   "   e   "   >   E   r   z   C   $   h
0000160  6c  65  72  3c  2f  6d  61  72  63  3a  73  75  62  66  69  65
          l   e   r   <   /   m   a   r   c   :   s   u   b   f   i   e
0000200  6c  64  3e  0d  0a  20  20  20  20  20  20  3c  6d  61  72  63
          l   d   >  cr  nl  sp  sp  sp  sp  sp  sp   <   m   a   r   c
0000220  3a  73  75  62  66  69  65  6c  64  20  63  6f  64  65  3d  22
          :   s   u   b   f   i   e   l   d  sp   c   o   d   e   =   "
0000240  65  22  3e  45  72  7a[[c3  a4]]68  6c  65  72  3c  2f  6d  61
          e   "   >   E   r   z   C   $   h   l   e   r   <   /   m   a
0000260  72  63  3a  73  75  62  66  69  65  6c  64  3e  0d  0a  20  20
          r   c   :   s   u   b   f   i   e   l   d   >  cr  nl  sp  sp
0000300  20  20  20  20  3c  6d  61  72  63  3a  73  75  62  66  69  65
         sp  sp  sp  sp   <   m   a   r   c   :   s   u   b   f   i   e
0000320  6c  64  20  63  6f  64  65  3d  22  65  22  3e  45  72  7a[[c3
          l   d  sp   c   o   d   e   =   "   e   "   >   E   r   z   C
0000340  a4]]68  6c  65  72  3c  2f  6d  61  72  63  3a  73  75  62  66
          $   h   l   e   r   <   /   m   a   r   c   :   s   u   b   f
0000360  69  65  6c  64  3e  0d  0a
          i   e   l   d   >  cr  nl

```
I've manually highlighted the occurrences of   c3 b6  and  c3 a4  above

**Comment by bpmph** [comment]
Thank you very much for your advice.

I tried a "to_utf8"-export changing your example command like this
java -jar marc4j-2.9.jar to_utf8 -normalize test/MARC_MARC8.mrc > marc_utf8.mrc

and the result looks just fine at the moment.

I will do some further tests and report back soon.

**Comment by bpmph** [comment]
Again, thank you very much for your help. 

The command above was just the solution i was looking for.
